version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  required:
    - build
    - repo
toolchain:
  name: 'add-toolchain-{{timestamp}}'
services:
  repo:
    service_id: bitbucket
    parameters:
      repo_name: '{{toolchain.name}}'
      repo_url: ''
      type: new
      has_issues: true
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{toolchain.name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          CF_APP: ''
          CF_SPACE_ID: ''
          CF_ORGANIZATION_ID: ''
          CF_API_URL: ''
          API_KEY: '{{form.pipeline.parameters.api-key}}'
        execute: false
  webide:
    service_id: orion
form:
  pipeline:
    parameters:
      pipeline_name: ''
    schema:
      $ref: deploy.json
